### ISSUE TITLE
Use GhostScript instead of poppler on macOS

### ISSUE THREAD

**Issue by Hawaiii** [ppwwyyxx/SoPaper#6]
Everything works on macOS now that I have updated pdftk and installed GhostScript with homebrew.

**Comment by ppwwyyxx** [comment]
Yes ps2pdf14 actually called gs, so it would be good to just replace ps2pdf14 completely.
What's the command you used with gs?
My observation is that ps2pdf14 converts pdf to 1.4 format and resize images to smaller resolution by default, so it usually reduce sizes.

**Comment by Hawaiii** [comment]
Erh it seems the result is the same with ps2pdf and ps2pdf14.
I didn't end up changing anything.
