### ISSUE TITLE
Test for file type on windows

### ISSUE THREAD

**Issue by moissinac** [ppwwyyxx/SoPaper#8]
Code 
            s = Popen('file "{0}"'.format(f.name),
                  stdout=PIPE, shell=True).stdout.read()
is platform specific
I suggest to add a switch in the config and to use
        if ukconfig.USE_PYPDF2:
            try:
                fo = open(f.name, "rb")
                PyPDF2.PdfFileReader(fo)
                s = "PDF document"
            except PyPDF2.utils.PdfReadError:
                s = "invalid PDF  file"
            finally:
                fo.close()
        else:
            s = Popen('file "{0}"'.format(f.name),
                  stdout=PIPE, shell=True).stdout.read()

**Comment by ppwwyyxx** [comment]
If you enable magic, it shouldn't go to that line.

**Comment by ppwwyyxx** [comment]
Could you install [python-magic](https://pypi.python.org/pypi/python-magic).
 Just add it as a dependency.

**Comment by moissinac** [comment]
I will try. But python-magic seems to be problematic to install on windows while pypdf2 is working and strightforward to install
